### ISSUE TITLE
Error while docker-compose up

### ISSUE THREAD

**Issue by yateenbbaluja** [shantanoo-desai/node-red-slim#4]
while docker-compose up. I am getting one error
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /docker/nodered/node-red/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/docker/nodered/node-red/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
yateen-nodered-image exited with code 254

Though I have this directory and under that I have package.json file with start script

**Comment by shantanoo-desai** [comment]
@yateenbbaluja have you tried building the image first? 

```bash
docker-compose build
```
